spring.application.name=deportivo

server.port=${PORT:8114}

spring.data.mongodb.uri=mongodb+srv://juan125esyeban_db_user:juanes098@cluster0.nofqkyo.mongodb.net/deportivo?retryWrites=true&w=majority

spring.thymeleaf.cache=false

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true